### ISSUE TITLE
setup.sh: no sudo for pip installation

### ISSUE THREAD

**Issue by janpb** [NCBI-Hackathons/VirusFriends#4]
Invoking `sudo` in setup.sh is uncomfortable, especially when trying to install VirusFriends on machines whose sysadmin on not your friend. 

Using `pip3 install  --user` (analogous to pip itself) should fix this, e.g.

*  `pip3 install pysam --user`
*  `pip3 install biopython --user`

This approach works on an Ubuntu or Arch Linux Docker container. 

I'll try to add this to a proper setup.sh and push ASAP.

**Comment by npbhavya** [comment]
fixed this
